Feature/request queue handle
iamr0man/github-HOF pull request #4
Opened 2023-02-04 12:07 UTC by iamr0man

2023-02-04 21:54 UTC, Rastopyr requested changes
Супер круто продвинулися. Черга працює, та можемо регулювати кількисть запитів.

Але треба ще дещо причесати.
- try/catch переробити на Promise
- типізувати чергу дженеріками
- використовати assert unreachable підхід

2023-02-04 21:54 UTC, Rastopyr commented on src/index.ts
> +    const taskCallbackMap: Record<string, (props?: any) => Promise<unknown>> = {
- any треба прибрати
- тут виходить що string може бути будь яким, і це не дуже добре з точки зору типів
- я би запропонував переобити на switch + enum

2023-02-04 21:54 UTC, Rastopyr commented on src/index.ts
> +      switch (task.name) {
Ось тут прямо є switch в якому можно викликати відповідну функцію, та мапіть в ней аргументи. Тобто одного switch має бути достатьно

2023-02-04 21:54 UTC, Rastopyr commented on src/index.ts
> +          return fn();
https://tinytip.co/tips/ts-switch-assert-unreachable/

Тут краще переробити на ось такий підхід. Раджу ознайомитися

2023-02-04 21:54 UTC, Rastopyr commented on src/index.ts
> +    queue.start();
Хай query/start повертає promise

2023-02-04 21:54 UTC, Rastopyr commented on src/index.ts
>    } catch (err) {
Я бі не загортав в try catch стільки коду.
Також якщо враховати що тут в тебе все побудовано на промізах, то краще це переписати десь на try/catch

2023-02-04 21:54 UTC, Rastopyr commented on src/queue/concurrentQueue.ts
> +    // this.waitingTask = [];
no needed

2023-02-04 21:54 UTC, Rastopyr commented on src/queue/concurrentQueue.types.ts
> +  fn: () => Promise<any>;
any прибираємо. Це все треба типізувати добре

2023-02-04 21:54 UTC, Rastopyr commented on src/queue/concurrentQueue.types.ts
>    err: Error | string | null;
В чому різниця між Error | string | null?
Чому err знаходится в типі який називається Params?
Здається тут треба одне відокремити від іньшого

2023-02-04 21:54 UTC, Rastopyr commented on src/queue/concurrentQueue.types.ts
> +export interface RateLimitResponse {
`RateLimit` та `RateLimitResponse` мені здається, це типи яки стосуються бізнес логіки

2023-02-06 15:51 UTC, iamr0man commented on src/queue/concurrentQueue.types.ts
> +export interface RateLimitResponse {
тому ці інтерфейси мають відображатись в іншому файлі, який стосується інтерфейсів сервісу по роботі з рейт лімітами ?

2023-02-06 15:52 UTC, iamr0man commented on src/queue/concurrentQueue.types.ts
>    err: Error | string | null;
це був інтерфейс для попередної черги, він використовувася для коллбеків

2023-02-06 15:53 UTC, iamr0man commented on src/index.ts
>    } catch (err) {
типу засунути всю логіку з промісами в іншу функцію, а вже новостворенну функцію обернути в try/catch ?

2023-02-06 15:56 UTC, Rastopyr commented on src/queue/concurrentQueue.types.ts
>    err: Error | string | null;
Давай те що не виористовивається. - приберемо

2023-02-06 15:56 UTC, Rastopyr commented on src/queue/concurrentQueue.types.ts
> +export interface RateLimitResponse {
Тому що поршується SRP. Черга має тільки ітеріровати таскі

2023-02-09 21:32 UTC, Rastopyr approved these changes

2023-02-12 17:17 UTC, merged