Feature/rate limit
iamr0man/github-HOF pull request #5
Opened 2023-02-13 16:19 UTC by iamr0man

Add logic that check rate limit availability before adding new repository or owner request.

2023-02-14 15:32 UTC, iamr0man commented on src/queue/handleRequests.ts
> +          }
```
if (Number(remainingRateLimit) === 0) {
            queue.clear();
            return {
              name: TaskName.CLEAR_QUEUE,
            };
          }
```

незнав як краще почистити чергу і повертати TaskResult тип. По суті CLEAR_QUEUE задача не відпрацьовує і не попадає в чергу. Так само написано для задачі з репозиторіями.

2023-02-14 16:35 UTC, Rastopyr requested changes

2023-02-14 16:35 UTC, Rastopyr commented on src/queue/handleRequests.ts
> +            queue.clear();
Extend `TaskRepository` to data about error. Clear error in onSucceed callback if error was provided

2023-02-14 16:35 UTC, Rastopyr commented on src/queue/newConcurrentQueue.ts
> +    queue.length = 0;
Reset queue value

2023-02-20 10:15 UTC, Rastopyr approved these changes
LGTM, є пара зауважень, але можемо рухатися далі

2023-02-20 10:15 UTC, Rastopyr commented on src/queue/handleRequests.ts
> +        if (isLastPage) {
Нагадай будь ласка, для чого тут цей кондішен?

2023-02-20 10:15 UTC, Rastopyr commented on src/queue/handleRequests.ts
>      if (isTaskRepository(value)) {
Тут краще використовувати switch

2023-02-20 10:15 UTC, Rastopyr commented on src/queue/handleRequests.ts
> -      const owner = ownerArray.find(
Я думаю, що цю логіку можно спробувати якось переписати, якщо буде час.
Бо ця логіка вкиористовує косвений еффект по назві.

2023-02-20 13:46 UTC, iamr0man commented on src/queue/handleRequests.ts
> +        if (isLastPage) {
моя помилка - щойно оновив. переніс логіку пагінації до того я робити реквест

ps раніше отримував 10 елементів, а записував скільки юзер запросив

2023-02-20 13:51 UTC, iamr0man commented on src/queue/handleRequests.ts
> -      const owner = ownerArray.find(
що маєш на увазі "косвений еффект по назві." ?

2023-02-21 16:14 UTC, Rastopyr commented on src/queue/handleRequests.ts
> -      const owner = ownerArray.find(
Ну я бачу таку проблему, що в масиві може бути дублікати. Це не проблема, але я б робив дата пайплайн де немає такой агрегації.

Але в данному контексті це не впливае на задачу, тому коментарь більш `nit`

2023-02-21 16:18 UTC, Rastopyr commented on src/queue/handleRequests.ts
>      if (isTaskRepository(value)) {
Бо треба робити switch по  `value.name`, тоді інформація про тип буде вичислятися правильно.

2023-02-22 13:32 UTC, merged